### PR TITLE
Bug fix #589. Workaround for line chart fill color

### LINKED ISSUE #589: Bug: Setting fill color on line chart corrupts chart in XLSX writer.
When setting the fill color property on a data series within a line chart and exporting it using the XLSX writer the chart becomes corrupt. The XLSX Chart writer has a bug on line:
https://github.com/PHPOffice/PhpSpreadsheet/blob/043327bb7dd4c4a8812c5b99b4ceb54647d77173/src/PhpSpreadsheet/Writer/Xlsx/Chart.php#L1079
It should not add the `<c:spPr />` tag with colour properties here. It should add them to the `<c:spPr />` tag generated for the line which occurs here:
https://github.com/PHPOffice/PhpSpreadsheet/blob/develop/src/PhpSpreadsheet/Writer/Xlsx/Chart.php#L1140

My workaround is to use a custom writer and I applied my fixes as below:
Line 1079:
```php
$plotLabel = $plotGroup->getPlotLabelByIndex($plotSeriesIdx);
if ($plotLabel && $groupType !== DataSeries::TYPE_LINECHART &&
    $groupType !== DataSeries::TYPE_STOCKCHART
) {
    $fillColor = $plotLabel->getFillColor();
    if ($fillColor !== null) {
        $objWriter->startElement('c:spPr');
        $objWriter->startElement('a:solidFill');
        $objWriter->startElement('a:srgbClr');
        $objWriter->writeAttribute('val', $fillColor);
        $objWriter->endElement();
        $objWriter->endElement();
        $objWriter->endElement();
    }
}
```

Line 1143:
```php
if ($groupType == DataSeries::TYPE_STOCKCHART) {
    $objWriter->startElement('a:noFill');
    $objWriter->endElement();
} elseif ($plotLabel && $plotLabel->getFillColor() !== null) {
    $objWriter->startElement('a:solidFill');
    $objWriter->startElement('a:srgbClr');
    $objWriter->writeAttribute('val', $plotLabel->getFillColor());
    $objWriter->endElement();
    $objWriter->endElement();
}
```

This probably isn't the best solution though as I don't know what impact it has on other chart types yet. I only know if affects line charts.

### PR DESCRIPTION
**Pull request by tiagomalheiro**
See #589

This is:

```
- [x] a bugfix
- [ ] a new feature
```

Checklist:

- [x] Changes are covered by unit tests
- [x] Code style is respected
- [x] Commit message explains **why** the change is made (see https://github.com/erlang/otp/wiki/Writing-good-commit-messages)
- [ ] CHANGELOG.md contains a short summary of the change
- [ ] Documentation is updated as necessary

### Why this change is needed?

When the fill color property of `DataSeries.plotLabel` using a DataSeriesValues on a line chart is set, the XLSX file written is corrupted, and MSExcel2016 removes the drawing1.xml if forced open.
 This problem was already documented on issue #589 along with a possible solution. So all credits go to @madrussa. I am only submitting the PR.
Used the sample file [33_Chart_create_line](https://github.com/PHPOffice/PhpSpreadsheet/blob/3ab066b7d6b073f110b21ed6f6b22e9df9cfa441/samples/Chart/33_Chart_create_line.php) to test it and modified it only to include fill color:
```php
// Set the Labels for each data series we want to plot
//     Datatype
//     Cell reference for data
//     Format Code
//     Number of datapoints in series
//     Data values
//     Data Marker
//     Fill Color
$dataSeriesLabels = [
    new DataSeriesValues(DataSeriesValues::DATASERIES_TYPE_STRING, 'Worksheet!$B$1', null, 1, [], null, '98B954'), // 2010
    new DataSeriesValues(DataSeriesValues::DATASERIES_TYPE_STRING, 'Worksheet!$C$1', null, 1, [], null, 'BE4B48'), // 2011
    new DataSeriesValues(DataSeriesValues::DATASERIES_TYPE_STRING, 'Worksheet!$D$1', null, 1, [], null, '4A7EBB'), // 2012
];
```

### CODE REVIEW

File: src/PhpSpreadsheet/Writer/Xlsx/Chart.php [hunk 1]
```diff
@@ -1144,6 +1144,13 @@ private function writePlotGroup($plotGroup, $groupType, $objWriter, &$catIsMulti
                 if ($groupType == DataSeries::TYPE_STOCKCHART) {
                     $objWriter->startElement('a:noFill');
                     $objWriter->endElement();
+                } elseif ($plotLabel && $plotLabel->getFillColor() !== null) {
+                    $fillColor = $plotLabel->getFillColor();
+                    $objWriter->startElement('a:solidFill');
+                    $objWriter->startElement('a:srgbClr');
+                    $objWriter->writeAttribute('val', $fillColor);
```
Comment (PowerKiKi) [inline src/PhpSpreadsheet/Writer/Xlsx/Chart.php:1151]: As PHPStan correctly reports, we need to handle the case where `getFillColor()` is an array. Also this should be covered by tests.

**Review by PowerKiKi — CHANGES_REQUESTED** [review]

File: src/PhpSpreadsheet/Writer/Xlsx/Chart.php [hunk 2]
```diff
@@ -1144,6 +1144,15 @@ private function writePlotGroup($plotGroup, $groupType, $objWriter, &$catIsMulti
                 if ($groupType == DataSeries::TYPE_STOCKCHART) {
                     $objWriter->startElement('a:noFill');
                     $objWriter->endElement();
+                } elseif ($plotLabel) {
+                    $fillColor = $plotLabel->getFillColor();
+                    if ($fillColor !== null && !is_array($fillColor)) {
```
Comment (PowerKiKi) [inline src/PhpSpreadsheet/Writer/Xlsx/Chart.php:1149]: I'd go for the more straightforward:

```suggestion
                    if (is_string($fillColor)) {
```

Comment (tiagomalheiro) [reply src/PhpSpreadsheet/Writer/Xlsx/Chart.php]: Totally agree. Commited, thanks
